CVParser {
    shape: class

    openFile(path: string): void
    closeFile(): void
    processFile(): unifiedCV
}

CVParserPDF {
    shape: class

    processFile(): unifiedCV
}

CVParserDoc {
    shape: class

    processFile(): unifiedCV
}

CVParserDoc -> CVParser {}

CVParserPDF -> CVParser {}
