@startuml

interface Component {
    + operation()
}

class ConcreteComponent {
    + operation()
}

class Decorator {
    + operation()
}

class ConcreteDecoratorA {
    + operation()
    - addedBehavior()
}

class ConcreteDecoratorB {
    - addedState
    + operation()
}

Component <|- ConcreteComponent
Component <|-- Decorator
Decorator *-- Component::operation
Decorator <|-- ConcreteDecoratorA
Decorator <|-- ConcreteDecoratorB

@enduml
